---
  version: '3.3'
  services:
    phpmyadmin:
      container_name: 'PROJECTNAAM-phpmyadmin'
      image: 'phpmyadmin/phpmyadmin'
      links:
        - db
      environment:
        PMA_HOST: PROJECTNAAM-wordpress-db
        PMA_USER: root
        PMA_PASSWORD: secret
        UPLOAD_LIMIT: 300M
      restart: always
      ports:
        - 8080:80
    db:   
      container_name: 'PROJECTNAAM-wordpress-db'
      image: 'mysql:5.7.16'
      volumes:
        - './data/mysql:/var/lib/mysql'
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: localdev
        MYSQL_USER: dev
        MYSQL_PASSWORD: secret
    wordpress:
      container_name: 'PROJECTNAAM-wordpress'
      depends_on:
        - db
      image: 'wordpress:latest'
      ports:
        - '80:80'
      environment:
        WORDPRESS_DB_HOST: 'db:3306'
        WORDPRESS_DB_USER: dev
        WORDPRESS_DB_PASSWORD: secret
        WORDPRESS_DB_NAME: localdev
        WORDPRESS_TABLE_PREFIX: PROJECTNAAMsite_
        WORDPRESS_DEBUG: 1
        XDEBUG_CONFIG: remote_host=host.docker.internal
        WORDPRESS_AUTH_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
        WORDPRESS_SECURE_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
        WORDPRESS_LOGGED_IN_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
        WORDPRESS_NONCE_KEY: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
        WORDPRESS_SECURE_AUTH_SALT: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
        WORDPRESS_LOGGED_IN_SALT: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
        WORDPRESS_NONCE_SALT: 5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
        WORDPRESS_CONFIG_EXTRA: |
          /* Development parameters */
          define('WP_CACHE', false);
          define('ENVIRONMENT', 'local');
          define('WP_DEBUG', true);
          define('WP_DEBUG_LOG', true);
          define('WP_DEBUG_DISPLAY', true);
          define('FS_METHOD', 'direct');
          define('WPCF7_LOAD_JS', false);

          /* Configure mailhog server */
          // SMTP Authentication
          define( 'SMTP_USER',   'jasperprikrio@gmail.com' );    // Username to use for SMTP authentication
          define( 'SMTP_PASS',   'czgxnptkcutahstq' );       // Password to use for SMTP authentication
          define( 'SMTP_HOST',   'smtp.gmail.com' );    // The hostname of the mail server
          define( 'SMTP_FROM',   'info@PROJECTNAAM.nl' ); // SMTP From email address
          define( 'SMTP_NAME',   'PROJECTNAAM' );    // SMTP From name
          define( 'SMTP_PORT',   '465' );                  // SMTP port number - likely to be 25, 465 or 587
          define( 'SMTP_SECURE', 'ssl' );                 // Encryption system to use - ssl or tls
          define( 'SMTP_AUTH',    true );                 // Use SMTP authentication (true|false)
          define( 'SMTP_DEBUG',   2 );                    // for debugging purposes only set to 1 or 2
          /* other wp-config defines here */
      volumes:
        - "./themes/:/var/www/html/wp-content/themes"
        - "./uploads/:/var/www/html/wp-content/uploads"
        - "./plugins/:/var/www/html/wp-content/plugins"
        - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        
        # uploads.ini: 
        # file_uploads = On
        # memory_limit = 64M
        # upload_max_filesize = 64M
        # post_max_size = 64M
        # max_execution_time = 600

        # Fix permissions for uploading content: https://stackoverflow.com/q/55747066 